using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AbmcTestDevEx.Models
{
    public class AbmcFlat
    {
        public class ContributorItemDetail2Connection1PropertiesConnectedTo
        {
            public int connectionId { get; set; }
            public bool isConnected { get; set; }
            public string parentTrimbleItemId { get; set; }
        }

        public class ContributorItemDetail2Connection2PropertiesConnectedTo
        {
            public int connectionId { get; set; }
            public bool isConnected { get; set; }
            public string parentTrimbleItemId { get; set; }
        }

        public class ContributorItemDetail2Connection3PropertiesConnectedTo
        {
            public int connectionId { get; set; }
            public bool isConnected { get; set; }
            public string parentTrimbleItemId { get; set; }
        }

        public class RootObject
        {
            public string TrimbleItemId { get; set; }
            public string Name { get; set; }
            public string FittingCategory { get; set; }
            public string FittingType { get; set; }
            public string ContributorItemDetail1ContributorId { get; set; }
            public string ContributorItemDetail1Id { get; set; }
            public string ContributorItemDetail1InsulationThickness { get; set; }
            public string ContributorItemDetail1LinerThickness { get; set; }
            public string ContributorItemDetail1LocationX { get; set; }
            public string ContributorItemDetail1LocationY { get; set; }
            public string ContributorItemDetail1LocationZ { get; set; }
            public string ContributorItemDetail1ModelChangeChangeId { get; set; }
            public string ContributorItemDetail1ModelChangeId { get; set; }
            public string ContributorItemDetail1ModelChangeTimeOfChange { get; set; }
            public string ContributorItemDetail1ModelChangeUserSessionId { get; set; }
            public string ContributorItemDetail1ModelChangeVersion { get; set; }
            public string ContributorItemDetail1PricingDiscountMultiplier { get; set; }
            public string ContributorItemDetail1PricingPikcCode { get; set; }
            public string ContributorItemDetail1PricingPrice { get; set; }
            public string ContributorItemDetail1PricingPriceCode { get; set; }
            public string ContributorItemDetail1PricingQuantity { get; set; }
            public string ContributorItemDetail1PricingTotalLaborCost { get; set; }
            public string ContributorItemDetail1PricingTotalLaborHours { get; set; }
            public string ContributorItemDetail1PricingUpcCode { get; set; }
            public string ContributorItemDetail1PropertiesTakeOffLineNum { get; set; }
            public string ContributorItemDetail1PropertiesMetric { get; set; }
            public string ContributorItemDetail1PropertiesAuditTrailID { get; set; }
            public string ContributorItemDetail1PropertiesAttachedToID { get; set; }
            public string ContributorItemDetail1PropertiesIsAttachedFrom { get; set; }
            public string ContributorItemDetail1PropertiesVertical { get; set; }
            public string ContributorItemDetail1PropertiesX { get; set; }
            public string ContributorItemDetail1PropertiesY { get; set; }
            public string ContributorItemDetail1PropertiesPipeX2 { get; set; }
            public string ContributorItemDetail1PropertiesPipeY2 { get; set; }
            public string ContributorItemDetail1PropertiesSizeStr { get; set; }
            public string ContributorItemDetail1PropertiesDrawing { get; set; }
            public string ContributorItemDetail1PropertiesAlternate { get; set; }
            public string ContributorItemDetail1PropertiesZone { get; set; }
            public string ContributorItemDetail1PropertiesSymbol { get; set; }
            public string ContributorItemDetail1PropertiesLine { get; set; }
            public string ContributorItemDetail1PropertiesReportCat { get; set; }
            public string ContributorItemDetail1PropertiesSpec { get; set; }
            public string ContributorItemDetail1PropertiesMaterialName { get; set; }
            public string ContributorItemDetail1PropertiesWeight { get; set; }
            public string ContributorItemDetail1PropertiesTrade { get; set; }
            public string ContributorItemDetail1PropertiesLocation { get; set; }
            public string ContributorItemDetail1PropertiesLaborField { get; set; }
            public string ContributorItemDetail1PropertiesLaborField_x0020__x0020_Shop { get; set; }
            public string ContributorItemDetail1PropertiesLaborShop { get; set; }
            public string ContributorItemDetail1PropertiesLaborField_x0020_Mat_x0020_Handling { get; set; }
            public string ContributorItemDetail1PropertiesLaborShop_x0020_Mat_x0020_Handling { get; set; }
            public string ContributorItemDetail1PropertiesLaborField_x0020_Mat_x0020_No_x0020_shop { get; set; }
            public string ContributorItemDetail1PropertiesLaborLabor_x0020_Cat_x0020_7 { get; set; }
            public string ContributorItemDetail1PropertiesLaborLabor_x0020_Cat_x0020_8 { get; set; }
            public string ContributorItemDetail1PropertiesPricingDiscountMultiplier { get; set; }
            public string ContributorItemDetail1PropertiesPricingPikcCode { get; set; }
            public string ContributorItemDetail1PropertiesPricingPrice { get; set; }
            public string ContributorItemDetail1PropertiesPricingPriceCode { get; set; }
            public string ContributorItemDetail1PropertiesPricingQuantity { get; set; }
            public string ContributorItemDetail1PropertiesPricingTotalLaborCost { get; set; }
            public string ContributorItemDetail1PropertiesPricingTotalLaborHours { get; set; }
            public string ContributorItemDetail1PropertiesPricingUpcCode { get; set; }
            public string ContributorItemDetail1PropertiesScopesSystem { get; set; }
            public string ContributorItemDetail1PropertiesScopesFloor { get; set; }
            public string ContributorItemDetail1ScopesSystem { get; set; }
            public string ContributorItemDetail1ScopesFloor { get; set; }
            public string ContributorItemDetail1TypeOfChange { get; set; }
            public string ContributorItemDetail1Units { get; set; }
            public string Version { get; set; }
            public string ContributorItemDetail1Connection1ConnectedToConnectionId { get; set; }
            public string ContributorItemDetail1Connection1ConnectedToIsConnected { get; set; }
            public string ContributorItemDetail1Connection1ConnectedToParentTrimbleItemId { get; set; }
            public string ContributorItemDetail1Connection1ConnectionDirectionX { get; set; }
            public string ContributorItemDetail1Connection1ConnectionDirectionY { get; set; }
            public string ContributorItemDetail1Connection1ConnectionDirectionZ { get; set; }
            public string ContributorItemDetail1Connection1ConnectionId { get; set; }
            public string ContributorItemDetail1Connection1ConnectionOtherDirectionX { get; set; }
            public string ContributorItemDetail1Connection1ConnectionOtherDirectionY { get; set; }
            public string ContributorItemDetail1Connection1ConnectionOtherDirectionZ { get; set; }
            public string ContributorItemDetail1Connection1Diameter { get; set; }
            public string ContributorItemDetail1Connection1Discipline { get; set; }
            public string ContributorItemDetail1Connection1Flow { get; set; }
            public string ContributorItemDetail1Connection1Height { get; set; }
            public string ContributorItemDetail1Connection1Inset { get; set; }
            public string ContributorItemDetail1Connection1IsConnected { get; set; }
            public string ContributorItemDetail1Connection1LocationX { get; set; }
            public string ContributorItemDetail1Connection1LocationY { get; set; }
            public string ContributorItemDetail1Connection1LocationZ { get; set; }
            public string ContributorItemDetail1Connection1Shape { get; set; }
            public string ContributorItemDetail1Connection1Slope { get; set; }
            public string ContributorItemDetail1Connection1Width { get; set; }
            public string ContributorItemDetail1Connection2ConnectedToConnectionId { get; set; }
            public string ContributorItemDetail1Connection2ConnectedToIsConnected { get; set; }
            public string ContributorItemDetail1Connection2ConnectedToParentTrimbleItemId { get; set; }
            public string ContributorItemDetail1Connection2ConnectionDirectionX { get; set; }
            public string ContributorItemDetail1Connection2ConnectionDirectionY { get; set; }
            public string ContributorItemDetail1Connection2ConnectionDirectionZ { get; set; }
            public string ContributorItemDetail1Connection2ConnectionId { get; set; }
            public string ContributorItemDetail1Connection2ConnectionOtherDirectionX { get; set; }
            public string ContributorItemDetail1Connection2ConnectionOtherDirectionY { get; set; }
            public string ContributorItemDetail1Connection2ConnectionOtherDirectionZ { get; set; }
            public string ContributorItemDetail1Connection2Diameter { get; set; }
            public string ContributorItemDetail1Connection2Discipline { get; set; }
            public string ContributorItemDetail1Connection2Flow { get; set; }
            public string ContributorItemDetail1Connection2Height { get; set; }
            public string ContributorItemDetail1Connection2Inset { get; set; }
            public string ContributorItemDetail1Connection2IsConnected { get; set; }
            public string ContributorItemDetail1Connection2LocationX { get; set; }
            public string ContributorItemDetail1Connection2LocationY { get; set; }
            public string ContributorItemDetail1Connection2LocationZ { get; set; }
            public string ContributorItemDetail1Connection2Shape { get; set; }
            public string ContributorItemDetail1Connection2Slope { get; set; }
            public string ContributorItemDetail1Connection2Width { get; set; }
            public string ContributorItemDetail1DimensionsLength { get; set; }
            public string ContributorItemDetail1PropertiesDimensionsLength { get; set; }
            public string ContributorItemDetail2Connection1ConnectedToConnectionId { get; set; }
            public string ContributorItemDetail2Connection1ConnectedToIsConnected { get; set; }
            public string ContributorItemDetail2Connection1ConnectedToParentTrimbleItemId { get; set; }
            public string ContributorItemDetail2Connection1ConnectionDirectionX { get; set; }
            public string ContributorItemDetail2Connection1ConnectionDirectionY { get; set; }
            public string ContributorItemDetail2Connection1ConnectionDirectionZ { get; set; }
            public string ContributorItemDetail2Connection1ConnectionId { get; set; }
            public string ContributorItemDetail2Connection1ConnectionOtherDirectionX { get; set; }
            public string ContributorItemDetail2Connection1ConnectionOtherDirectionY { get; set; }
            public string ContributorItemDetail2Connection1ConnectionOtherDirectionZ { get; set; }
            public string ContributorItemDetail2Connection1Diameter { get; set; }
            public string ContributorItemDetail2Connection1Discipline { get; set; }
            public string ContributorItemDetail2Connection1Flow { get; set; }
            public string ContributorItemDetail2Connection1Height { get; set; }
            public string ContributorItemDetail2Connection1Inset { get; set; }
            public string ContributorItemDetail2Connection1IsConnected { get; set; }
            public string ContributorItemDetail2Connection1LocationX { get; set; }
            public string ContributorItemDetail2Connection1LocationY { get; set; }
            public string ContributorItemDetail2Connection1LocationZ { get; set; }
            public string ContributorItemDetail2Connection1PropertiesAngle { get; set; }
            public string ContributorItemDetail2Connection1PropertiesConnectionDirectionX { get; set; }
            public string ContributorItemDetail2Connection1PropertiesConnectionDirectionY { get; set; }
            public string ContributorItemDetail2Connection1PropertiesConnectionDirectionZ { get; set; }
            public string ContributorItemDetail2Connection1PropertiesConnectionOtherDirectionX { get; set; }
            public string ContributorItemDetail2Connection1PropertiesConnectionOtherDirectionY { get; set; }
            public string ContributorItemDetail2Connection1PropertiesConnectionOtherDirectionZ { get; set; }
            public ContributorItemDetail2Connection1PropertiesConnectedTo ContributorItemDetail2Connection1PropertiesConnectedTo { get; set; }
            public string ContributorItemDetail2Connection1PropertiesDescription { get; set; }
            public string ContributorItemDetail2Connection1PropertiesDiameter { get; set; }
            public string ContributorItemDetail2Connection1PropertiesFlow { get; set; }
            public string ContributorItemDetail2Connection1PropertiesFlowDirection { get; set; }
            public string ContributorItemDetail2Connection1PropertiesHeight { get; set; }
            public string ContributorItemDetail2Connection1PropertiesInset { get; set; }
            public string ContributorItemDetail2Connection1PropertiesIsConnected { get; set; }
            public string ContributorItemDetail2Connection1PropertiesIsMovable { get; set; }
            public string ContributorItemDetail2Connection1PropertiesIsUtilityConnector { get; set; }
            public string ContributorItemDetail2Connection1PropertiesLocationX { get; set; }
            public string ContributorItemDetail2Connection1PropertiesLocationY { get; set; }
            public string ContributorItemDetail2Connection1PropertiesLocationZ { get; set; }
            public string ContributorItemDetail2Connection1PropertiesMEPSystem { get; set; }
            public string ContributorItemDetail2Connection1PropertiesParentTrimbleItemId { get; set; }
            public string ContributorItemDetail2Connection1PropertiesPressureDrop { get; set; }
            public string ContributorItemDetail2Connection1PropertiesSlope { get; set; }
            public string ContributorItemDetail2Connection1PropertiesSystem { get; set; }
            public string ContributorItemDetail2Connection1PropertiesVelocityPressure { get; set; }
            public string ContributorItemDetail2Connection1PropertiesWidth { get; set; }
            public string ContributorItemDetail2Connection1Shape { get; set; }
            public string ContributorItemDetail2Connection1Slope { get; set; }
            public string ContributorItemDetail2Connection1System { get; set; }
            public string ContributorItemDetail2Connection1Width { get; set; }
            public string ContributorItemDetail2Connection2ConnectedToConnectionId { get; set; }
            public string ContributorItemDetail2Connection2ConnectedToIsConnected { get; set; }
            public string ContributorItemDetail2Connection2ConnectedToParentTrimbleItemId { get; set; }
            public string ContributorItemDetail2Connection2ConnectionDirectionX { get; set; }
            public string ContributorItemDetail2Connection2ConnectionDirectionY { get; set; }
            public string ContributorItemDetail2Connection2ConnectionDirectionZ { get; set; }
            public string ContributorItemDetail2Connection2ConnectionId { get; set; }
            public string ContributorItemDetail2Connection2ConnectionOtherDirectionX { get; set; }
            public string ContributorItemDetail2Connection2ConnectionOtherDirectionY { get; set; }
            public string ContributorItemDetail2Connection2ConnectionOtherDirectionZ { get; set; }
            public string ContributorItemDetail2Connection2Diameter { get; set; }
            public string ContributorItemDetail2Connection2Discipline { get; set; }
            public string ContributorItemDetail2Connection2Flow { get; set; }
            public string ContributorItemDetail2Connection2Height { get; set; }
            public string ContributorItemDetail2Connection2Inset { get; set; }
            public string ContributorItemDetail2Connection2IsConnected { get; set; }
            public string ContributorItemDetail2Connection2LocationX { get; set; }
            public string ContributorItemDetail2Connection2LocationY { get; set; }
            public string ContributorItemDetail2Connection2LocationZ { get; set; }
            public string ContributorItemDetail2Connection2PropertiesAngle { get; set; }
            public string ContributorItemDetail2Connection2PropertiesConnectionDirectionX { get; set; }
            public string ContributorItemDetail2Connection2PropertiesConnectionDirectionY { get; set; }
            public string ContributorItemDetail2Connection2PropertiesConnectionDirectionZ { get; set; }
            public string ContributorItemDetail2Connection2PropertiesConnectionOtherDirectionX { get; set; }
            public string ContributorItemDetail2Connection2PropertiesConnectionOtherDirectionY { get; set; }
            public string ContributorItemDetail2Connection2PropertiesConnectionOtherDirectionZ { get; set; }
            public ContributorItemDetail2Connection2PropertiesConnectedTo ContributorItemDetail2Connection2PropertiesConnectedTo { get; set; }
            public string ContributorItemDetail2Connection2PropertiesDescription { get; set; }
            public string ContributorItemDetail2Connection2PropertiesDiameter { get; set; }
            public string ContributorItemDetail2Connection2PropertiesFlow { get; set; }
            public string ContributorItemDetail2Connection2PropertiesFlowDirection { get; set; }
            public string ContributorItemDetail2Connection2PropertiesHeight { get; set; }
            public string ContributorItemDetail2Connection2PropertiesInset { get; set; }
            public string ContributorItemDetail2Connection2PropertiesIsConnected { get; set; }
            public string ContributorItemDetail2Connection2PropertiesIsMovable { get; set; }
            public string ContributorItemDetail2Connection2PropertiesIsUtilityConnector { get; set; }
            public string ContributorItemDetail2Connection2PropertiesLocationX { get; set; }
            public string ContributorItemDetail2Connection2PropertiesLocationY { get; set; }
            public string ContributorItemDetail2Connection2PropertiesLocationZ { get; set; }
            public string ContributorItemDetail2Connection2PropertiesMEPSystem { get; set; }
            public string ContributorItemDetail2Connection2PropertiesParentTrimbleItemId { get; set; }
            public string ContributorItemDetail2Connection2PropertiesPressureDrop { get; set; }
            public string ContributorItemDetail2Connection2PropertiesSlope { get; set; }
            public string ContributorItemDetail2Connection2PropertiesSystem { get; set; }
            public string ContributorItemDetail2Connection2PropertiesVelocityPressure { get; set; }
            public string ContributorItemDetail2Connection2PropertiesWidth { get; set; }
            public string ContributorItemDetail2Connection2Shape { get; set; }
            public string ContributorItemDetail2Connection2Slope { get; set; }
            public string ContributorItemDetail2Connection2System { get; set; }
            public string ContributorItemDetail2Connection2Width { get; set; }
            public string ContributorItemDetail2ContributorId { get; set; }
            public string ContributorItemDetail2Id { get; set; }
            public string ContributorItemDetail2InsulationThickness { get; set; }
            public string ContributorItemDetail2LinerThickness { get; set; }
            public string ContributorItemDetail2LocationX { get; set; }
            public string ContributorItemDetail2LocationY { get; set; }
            public string ContributorItemDetail2LocationZ { get; set; }
            public string ContributorItemDetail2ModelChangeChangeId { get; set; }
            public string ContributorItemDetail2ModelChangeId { get; set; }
            public string ContributorItemDetail2ModelChangeTimeOfChange { get; set; }
            public string ContributorItemDetail2ModelChangeUserSessionId { get; set; }
            public string ContributorItemDetail2ModelChangeVersion { get; set; }
            public string ContributorItemDetail2PropertiesCenterElevation { get; set; }
            public string ContributorItemDetail2PropertiesInsulationThickness { get; set; }
            public string ContributorItemDetail2PropertiesLevel { get; set; }
            public string ContributorItemDetail2PropertiesLevelOffset { get; set; }
            public string ContributorItemDetail2PropertiesLiningThickness { get; set; }
            public string ContributorItemDetail2PropertiesLocationX { get; set; }
            public string ContributorItemDetail2PropertiesLocationY { get; set; }
            public string ContributorItemDetail2PropertiesLocationZ { get; set; }
            public string ContributorItemDetail2PropertiesRevitElementId { get; set; }
            public string ContributorItemDetail2PropertiesRevitElementUniqueId { get; set; }
            public string ContributorItemDetail2PropertiesScopesSystem { get; set; }
            public string ContributorItemDetail2PropertiesScopesFloor { get; set; }
            public string ContributorItemDetail2PropertiesScopesRoom { get; set; }
            public string ContributorItemDetail2PropertiesScopesSpace { get; set; }
            public string ContributorItemDetail2PropertiesSystem_x0020_Abbreviation { get; set; }
            public string ContributorItemDetail2PropertiesOverall_x0020_Size { get; set; }
            public string ContributorItemDetail2PropertiesTrimble_x0020_Item_x0020_Id { get; set; }
            public string ContributorItemDetail2PropertiesFamily_x0020_and_x0020_Type { get; set; }
            public string ContributorItemDetail2PropertiesSegment_x0020_Description { get; set; }
            public string ContributorItemDetail2PropertiesPipe_x0020_Segment { get; set; }
            public string ContributorItemDetail2PropertiesSchedule_x002F_Type { get; set; }
            public string ContributorItemDetail2PropertiesRoughness { get; set; }
            public string ContributorItemDetail2PropertiesSlope { get; set; }
            public string ContributorItemDetail2PropertiesType { get; set; }
            public string ContributorItemDetail2PropertiesCritical_x0020_Path { get; set; }
            public string ContributorItemDetail2PropertiesVertical_x0020_Justification { get; set; }
            public string ContributorItemDetail2PropertiesMaterial { get; set; }
            public string ContributorItemDetail2PropertiesFamily_x0020_Name { get; set; }
            public string ContributorItemDetail2PropertiesAdditional_x0020_Flow { get; set; }
            public string ContributorItemDetail2PropertiesSize { get; set; }
            public string ContributorItemDetail2PropertiesFriction { get; set; }
            public string ContributorItemDetail2PropertiesEnd_x0020_Offset { get; set; }
            public string ContributorItemDetail2PropertiesType_x0020_Name { get; set; }
            public string ContributorItemDetail2PropertiesInside_x0020_Diameter { get; set; }
            public string ContributorItemDetail2PropertiesVelocity { get; set; }
            public string ContributorItemDetail2PropertiesStart_x0020_Offset { get; set; }
            public string ContributorItemDetail2PropertiesType_x0020_Id { get; set; }
            public string ContributorItemDetail2PropertiesInvert_x0020_Elevation { get; set; }
            public string ContributorItemDetail2PropertiesFlow { get; set; }
            public string ContributorItemDetail2PropertiesFlow_x0020_State { get; set; }
            public string ContributorItemDetail2PropertiesSystem_x0020_Type { get; set; }
            public string ContributorItemDetail2PropertiesSystem_x0020_Name { get; set; }
            public string ContributorItemDetail2PropertiesFamily { get; set; }
            public string ContributorItemDetail2PropertiesConnection_x0020_Type { get; set; }
            public string ContributorItemDetail2PropertiesRelative_x0020_Roughness { get; set; }
            public string ContributorItemDetail2PropertiesDiameter { get; set; }
            public string ContributorItemDetail2PropertiesReynolds_x0020_Number { get; set; }
            public string ContributorItemDetail2PropertiesPressure_x0020_Drop { get; set; }
            public string ContributorItemDetail2PropertiesArea { get; set; }
            public string ContributorItemDetail2PropertiesFriction_x0020_Factor { get; set; }
            public string ContributorItemDetail2PropertiesReference_x0020_Level { get; set; }
            public string ContributorItemDetail2PropertiesLength { get; set; }
            public string ContributorItemDetail2PropertiesHorizontal_x0020_Justification { get; set; }
            public string ContributorItemDetail2PropertiesOutside_x0020_Diameter { get; set; }
            public string ContributorItemDetail2PropertiesOffset { get; set; }
            public string ContributorItemDetail2PropertiesPhase_x0020_Created { get; set; }
            public string ContributorItemDetail2PropertiesSection { get; set; }
            public string ContributorItemDetail2PropertiesCost { get; set; }
            public string ContributorItemDetail2PropertiesAssembly_x0020_Description { get; set; }
            public string ContributorItemDetail2PropertiesAssembly_x0020_Code { get; set; }
            public string ContributorItemDetail2ScopesSystem { get; set; }
            public string ContributorItemDetail2ScopesFloor { get; set; }
            public string ContributorItemDetail2ScopesRoom { get; set; }
            public string ContributorItemDetail2ScopesSpace { get; set; }
            public string ContributorItemDetail2TypeOfChange { get; set; }
            public string ContributorItemDetail2Units { get; set; }
            public string ContributorItemDetail2PropertiesURL { get; set; }
            public string ContributorItemDetail1DimensionsAngle { get; set; }
            public string ContributorItemDetail1PropertiesDimensionsAngle { get; set; }
            public string ContributorItemDetail2DimensionsAngle { get; set; }
            public string ContributorItemDetail2DimensionsCenterLineRadius { get; set; }
            public string ContributorItemDetail2PropertiesDimensionsAngle { get; set; }
            public string ContributorItemDetail2PropertiesDimensionsCenterLineRadius { get; set; }
            public string ContributorItemDetail2PropertiesPIPEID2 { get; set; }
            public string ContributorItemDetail2PropertiesAllow_x0020_Slope_x0020_Adjustments { get; set; }
            public string ContributorItemDetail2PropertiesNom_x0020_Radius2 { get; set; }
            public string ContributorItemDetail2PropertiesExt1 { get; set; }
            public string ContributorItemDetail2PropertiesConnector1 { get; set; }
            public string ContributorItemDetail2PropertiesConnector2 { get; set; }
            public string ContributorItemDetail2Properties24C15 { get; set; }
            public string ContributorItemDetail2PropertiesC2E { get; set; }
            public string ContributorItemDetail2PropertiesSpool_x0020_Tag { get; set; }
            public string ContributorItemDetail2PropertiesButt_x0020_Weld { get; set; }
            public string ContributorItemDetail2PropertiesC2E2 { get; set; }
            public string ContributorItemDetail2PropertiesHID2 { get; set; }
            public string ContributorItemDetail2PropertiesNotes { get; set; }
            public string ContributorItemDetail2PropertiesDiameter1 { get; set; }
            public string ContributorItemDetail2Properties24DLB { get; set; }
            public string ContributorItemDetail2PropertiesIsCustom { get; set; }
            public string ContributorItemDetail2PropertiesPIPEOD1 { get; set; }
            public string ContributorItemDetail2PropertiesPipeOD2 { get; set; }
            public string ContributorItemDetail2PropertiesCtoE2 { get; set; }
            public string ContributorItemDetail2PropertiesTick1 { get; set; }
            public string ContributorItemDetail2PropertiesPurchasedFitting { get; set; }
            public string ContributorItemDetail2PropertiesPIPEID1 { get; set; }
            public string ContributorItemDetail2PropertiesCtoE1 { get; set; }
            public string ContributorItemDetail2PropertiesNom_x0020_Radius1 { get; set; }
            public string ContributorItemDetail2PropertiesExt { get; set; }
            public string ContributorItemDetail2PropertiesItem_x0020_Number { get; set; }
            public string ContributorItemDetail2PropertiesHost { get; set; }
            public string ContributorItemDetail2PropertiesVolume { get; set; }
            public string ContributorItemDetail2PropertiesBend_x0020_Radius { get; set; }
            public string ContributorItemDetail2PropertiesGroup_x0020_Number { get; set; }
            public string ContributorItemDetail2PropertiesMinimum_x0020_Size { get; set; }
            public string ContributorItemDetail2PropertiesPiece_x0020_Number { get; set; }
            public string ContributorItemDetail2PropertiesC2E1 { get; set; }
            public string ContributorItemDetail2PropertiesHOD1 { get; set; }
            public string ContributorItemDetail2PropertiesLoss_x0020_Method { get; set; }
            public string ContributorItemDetail2PropertiesBW { get; set; }
            public string ContributorItemDetail2PropertiesMale1 { get; set; }
            public string ContributorItemDetail2PropertiesHID1 { get; set; }
            public string ContributorItemDetail2PropertiesUse_x0020_Annotation_x0020_Scale { get; set; }
            public string ContributorItemDetail2PropertiesAngle2 { get; set; }
            public string ContributorItemDetail2Properties24DWS { get; set; }
            public string ContributorItemDetail2PropertiesMale2 { get; set; }
            public string ContributorItemDetail2PropertiesTickBR { get; set; }
            public string ContributorItemDetail2PropertiesExt2 { get; set; }
            public string ContributorItemDetail2PropertiesDiameter2 { get; set; }
            public string ContributorItemDetail2PropertiesHOD2 { get; set; }
            public string ContributorItemDetail2PropertiesWeight { get; set; }
            public string ContributorItemDetail2PropertiesNominal_x0020_Size { get; set; }
            public string ContributorItemDetail2PropertiesMaximum_x0020_Size { get; set; }
            public string ContributorItemDetail2PropertiesAngle1 { get; set; }
            public string ContributorItemDetail2PropertiesTick2 { get; set; }
            public string ContributorItemDetail2PropertiesID { get; set; }
            public string ContributorItemDetail2PropertiesProduct_x0020_Description { get; set; }
            public string ContributorItemDetail2PropertiesK_x0020_Coefficient_x0020_Table { get; set; }
            public string ContributorItemDetail2PropertiesOrder { get; set; }
            public string ContributorItemDetail2PropertiesLookup_x0020_Table_x0020_Name { get; set; }
            public string ContributorItemDetail2PropertiesOmniClass_x0020_Number { get; set; }
            public string ContributorItemDetail2PropertiesOmniClass_x0020_Title { get; set; }
            public string ContributorItemDetail2PropertiesK_x0020_Coefficient { get; set; }
            public string ContributorItemDetail2PropertiesCode_x0020_Name { get; set; }
            public string ContributorItemDetail2PropertiesBDW { get; set; }
            public string ContributorItemDetail2PropertiesManufacturer_x0020_Name { get; set; }
            public string ContributorItemDetail1Connection3ConnectedToConnectionId { get; set; }
            public string ContributorItemDetail1Connection3ConnectedToIsConnected { get; set; }
            public string ContributorItemDetail1Connection3ConnectedToParentTrimbleItemId { get; set; }
            public string ContributorItemDetail1Connection3ConnectionDirectionX { get; set; }
            public string ContributorItemDetail1Connection3ConnectionDirectionY { get; set; }
            public string ContributorItemDetail1Connection3ConnectionDirectionZ { get; set; }
            public string ContributorItemDetail1Connection3ConnectionId { get; set; }
            public string ContributorItemDetail1Connection3ConnectionOtherDirectionX { get; set; }
            public string ContributorItemDetail1Connection3ConnectionOtherDirectionY { get; set; }
            public string ContributorItemDetail1Connection3ConnectionOtherDirectionZ { get; set; }
            public string ContributorItemDetail1Connection3Diameter { get; set; }
            public string ContributorItemDetail1Connection3Discipline { get; set; }
            public string ContributorItemDetail1Connection3Flow { get; set; }
            public string ContributorItemDetail1Connection3Height { get; set; }
            public string ContributorItemDetail1Connection3Inset { get; set; }
            public string ContributorItemDetail1Connection3IsConnected { get; set; }
            public string ContributorItemDetail1Connection3LocationX { get; set; }
            public string ContributorItemDetail1Connection3LocationY { get; set; }
            public string ContributorItemDetail1Connection3LocationZ { get; set; }
            public string ContributorItemDetail1Connection3Shape { get; set; }
            public string ContributorItemDetail1Connection3Slope { get; set; }
            public string ContributorItemDetail1Connection3Width { get; set; }
            public string ContributorItemDetail2Connection3ConnectedToConnectionId { get; set; }
            public string ContributorItemDetail2Connection3ConnectedToIsConnected { get; set; }
            public string ContributorItemDetail2Connection3ConnectedToParentTrimbleItemId { get; set; }
            public string ContributorItemDetail2Connection3ConnectionDirectionX { get; set; }
            public string ContributorItemDetail2Connection3ConnectionDirectionY { get; set; }
            public string ContributorItemDetail2Connection3ConnectionDirectionZ { get; set; }
            public string ContributorItemDetail2Connection3ConnectionId { get; set; }
            public string ContributorItemDetail2Connection3ConnectionOtherDirectionX { get; set; }
            public string ContributorItemDetail2Connection3ConnectionOtherDirectionY { get; set; }
            public string ContributorItemDetail2Connection3ConnectionOtherDirectionZ { get; set; }
            public string ContributorItemDetail2Connection3Diameter { get; set; }
            public string ContributorItemDetail2Connection3Discipline { get; set; }
            public string ContributorItemDetail2Connection3Flow { get; set; }
            public string ContributorItemDetail2Connection3Height { get; set; }
            public string ContributorItemDetail2Connection3Inset { get; set; }
            public string ContributorItemDetail2Connection3IsConnected { get; set; }
            public string ContributorItemDetail2Connection3LocationX { get; set; }
            public string ContributorItemDetail2Connection3LocationY { get; set; }
            public string ContributorItemDetail2Connection3LocationZ { get; set; }
            public string ContributorItemDetail2Connection3PropertiesAngle { get; set; }
            public string ContributorItemDetail2Connection3PropertiesConnectionDirectionX { get; set; }
            public string ContributorItemDetail2Connection3PropertiesConnectionDirectionY { get; set; }
            public string ContributorItemDetail2Connection3PropertiesConnectionDirectionZ { get; set; }
            public string ContributorItemDetail2Connection3PropertiesConnectionOtherDirectionX { get; set; }
            public string ContributorItemDetail2Connection3PropertiesConnectionOtherDirectionY { get; set; }
            public string ContributorItemDetail2Connection3PropertiesConnectionOtherDirectionZ { get; set; }
            public ContributorItemDetail2Connection3PropertiesConnectedTo ContributorItemDetail2Connection3PropertiesConnectedTo { get; set; }
            public string ContributorItemDetail2Connection3PropertiesDescription { get; set; }
            public string ContributorItemDetail2Connection3PropertiesDiameter { get; set; }
            public string ContributorItemDetail2Connection3PropertiesFlow { get; set; }
            public string ContributorItemDetail2Connection3PropertiesFlowDirection { get; set; }
            public string ContributorItemDetail2Connection3PropertiesHeight { get; set; }
            public string ContributorItemDetail2Connection3PropertiesInset { get; set; }
            public string ContributorItemDetail2Connection3PropertiesIsConnected { get; set; }
            public string ContributorItemDetail2Connection3PropertiesIsMovable { get; set; }
            public string ContributorItemDetail2Connection3PropertiesIsUtilityConnector { get; set; }
            public string ContributorItemDetail2Connection3PropertiesLocationX { get; set; }
            public string ContributorItemDetail2Connection3PropertiesLocationY { get; set; }
            public string ContributorItemDetail2Connection3PropertiesLocationZ { get; set; }
            public string ContributorItemDetail2Connection3PropertiesMEPSystem { get; set; }
            public string ContributorItemDetail2Connection3PropertiesParentTrimbleItemId { get; set; }
            public string ContributorItemDetail2Connection3PropertiesPressureDrop { get; set; }
            public string ContributorItemDetail2Connection3PropertiesSlope { get; set; }
            public string ContributorItemDetail2Connection3PropertiesSystem { get; set; }
            public string ContributorItemDetail2Connection3PropertiesVelocityPressure { get; set; }
            public string ContributorItemDetail2Connection3PropertiesWidth { get; set; }
            public string ContributorItemDetail2Connection3Shape { get; set; }
            public string ContributorItemDetail2Connection3Slope { get; set; }
            public string ContributorItemDetail2Connection3System { get; set; }
            public string ContributorItemDetail2Connection3Width { get; set; }
            public string ContributorItemDetail2PropertiesCenter_x0020_to_x0020_End { get; set; }
            public string ContributorItemDetail2PropertiesFitting_x0020_Outside_x0020_Diameter { get; set; }
            public string ContributorItemDetail2PropertiesFitting_x0020_Outside_x0020_Radius { get; set; }
            public string ContributorItemDetail2PropertiesNominal_x0020_Diameter { get; set; }
            public string ContributorItemDetail2PropertiesCenter_x0020_to_x0020_End_x0020_Label { get; set; }
            public string ContributorItemDetail2PropertiesNominal_x0020_Radius { get; set; }
            public string ContributorItemDetail2PropertiesTick_x0020_Size { get; set; }
            public string ContributorItemDetail2PropertiesAngle_x0020_1 { get; set; }
            public string ContributorItemDetail2PropertiesGender_x0020_Type { get; set; }
            public string ContributorItemDetail2PropertiesWatermarked_x0020_By { get; set; }
        }
    }
}
